// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwJhP3aCSxagQMkOdtHlinl5dElrrEVZ8',
    appId: '1:487882044497:web:502625ee0ac5ce28d8b470',
    messagingSenderId: '487882044497',
    projectId: 'flutter-chatapp-6c836',
    authDomain: 'flutter-chatapp-6c836.firebaseapp.com',
    storageBucket: 'flutter-chatapp-6c836.appspot.com',
    measurementId: 'G-NF15FKX7KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoBE4mfvSfJQZex_sCFeA7GE-JIE849AE',
    appId: '1:487882044497:android:1590de34e59914f8d8b470',
    messagingSenderId: '487882044497',
    projectId: 'flutter-chatapp-6c836',
    storageBucket: 'flutter-chatapp-6c836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbgvBCn2q-YRgwIlPQTrsfeo1hNrKvdUg',
    appId: '1:487882044497:ios:565f87e6df634925d8b470',
    messagingSenderId: '487882044497',
    projectId: 'flutter-chatapp-6c836',
    storageBucket: 'flutter-chatapp-6c836.appspot.com',
    iosBundleId: 'com.example.flutterChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwJhP3aCSxagQMkOdtHlinl5dElrrEVZ8',
    appId: '1:487882044497:web:22875b40e50bf893d8b470',
    messagingSenderId: '487882044497',
    projectId: 'flutter-chatapp-6c836',
    authDomain: 'flutter-chatapp-6c836.firebaseapp.com',
    storageBucket: 'flutter-chatapp-6c836.appspot.com',
    measurementId: 'G-S84EW1XC1Q',
  );
}
